# evidence-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: evidence-pod
spec:
  volumes:
    - name: project-data
      hostPath:
        path: /home/snowpoke/source/repos/project-health-analyzer
        type: Directory
    - name: sources-data
      hostPath:
        path: /home/snowpoke/source/repos/project-health-analyzer/sources
        type: Directory
  containers:
    - name: evidence-app
      image: evidencedev/devenv:latest
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - mountPath: /app
          name: project-data
        - mountPath: /app/sources
          name: sources-data
      workingDir: /app
      command: ["/bin/bash"]
      args: ["-c", "npm install && npm run sources && npm run dev -- --host"]
